name: tests and lint

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: npm install
        # Install project
        run: |
            make install

      # Runs eslint
      - name: Run eslint
        run: make lint

      # Runs test
      - name: Run test
        run: make test

     # Runs test-coverage
     - name: Run test-coverage
       run: make test-coverage
